Refacto code
139bercy/secret_stat pull request #16
Opened 2021-03-05 13:28 UTC by kaa-serpent

code refacto, permet de gérer un plus grand nombre de cas
je met la documentation à jour

2021-03-05 13:39 UTC, kaa-serpent commented
oups j'ai oublié de renomer une variable

2021-03-08 10:53 UTC, desrousseaux requested changes

2021-03-08 10:53 UTC, desrousseaux commented on aggregation.py
> +        df_percent.loc[df_percent[col_secret] >= 85] = np.nan
mettre le 85 en argument

2021-03-08 10:53 UTC, desrousseaux commented on aggregation.py
> +        df_count.loc[df_count[col_secret] <= 3] = np.nan
mettre le 3 en argument

2021-03-09 10:58 UTC, desrousseaux approved these changes

2021-03-09 10:59 UTC, merged